version: '3'
services:
  api:
    build: ./services/people
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=db
      - SECRET_KEY=my_precious
    volumes:
      - './services/people:/usr/src/app'
    links:
      - db
  db:
    image: mongo:4.0
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - api
      - client
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client/public:/usr/src/app/public'
      - './services/client/src:/usr/src/app/src'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - api
  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    ports:
      - 3008:8080
    environment:
      - URL=https://petstore.swagger.io/v2/swagger.json
    depends_on:
      - api