version: '3'
services:
  people:
    build:
      context: ./services/people
      dockerfile: Dockerfile-stage
    expose:
      - "5000"
    environment:
      - FLASK_ENV=prod
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=people-db
      - SECRET_KEY=my_precious
    links:
      - people-db
  people-db:
    image: mongo:4.0
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - people
      - client
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - people
  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - people