version: '3'
services:
  people:
    build: ./services/people
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=people-db
      - SECRET_KEY=my_precious
    volumes:
      - './services/people:/usr/src/app'
    links:
      - people-db
  people-db:
    image: mongo:4.0
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - people
      - client
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client/public:/usr/src/app/public'
      - './services/client/src:/usr/src/app/src'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - people
  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
      - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - people