version: '3'
services:
  people:
    build: ./services/people
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=people-db
      - DATABASE_NAME=dev
      - DATABASE_TEST_NAME=test
      - SECRET_KEY=my_precious
    volumes:
      - './services/people:/usr/src/app'
    links:
      - people-db

  people-db:
    image: mongo:4.0

  tasks:
    build: ./services/tasks
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=tasks-db
      - SECRET_KEY=my_precious
    volumes:
      - './services/tasks:/usr/src/app'
    links:
      - tasks-db
  tasks-db:
    image: mongo:4.0

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 80:80
    depends_on: 
      - people
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client/public:/usr/src/app/public'
      - './services/client/src:/usr/src/app/src'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - people

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
      - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - people

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9999
      KAFKA_CREATE_TOPICS: test-topic-1:1:2,test-topic-2:1:2,test-topic-3:1:2


  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true