version: '3'
services:
  web:
    build: ./peopleui
    image: peopleui
    volumes:
      - ./peopleui:/app
      - '/app/node_modules'
    ports:
      - "3000:3000"
    links:
      - api
  api:
    build: ./api
    command: python -u app.py
    ports:
      - "80:5000"
    volumes:
      - ./api:/todo
    links:
      - db
  db:
    image: mongo:3.0.2